from datetime import datetime
import functools
import os.path
import requests

# from util import get_environ_file_path
from APIStockServer.modules.util import get_environ_file_path


# Not using decorator package because of exception generation on calling decorated function
# (which appear to have missing argument when called - this missing argument is generated by decorator: cls._init_req())
def api_request(function):
    @functools.wraps(function)
    def wrapper(cls, *args, **kwargs):
        """
        :param cls: ApiHandler class
        """
        try:
            cls._auth_key_file() if not cls._is_auth_key() else None
            return function(cls, cls._init_req(), *args, **kwargs)
        except KeyError as e:
            raise Exception('Request cannot be performed due to authentication key missing.').\
                with_traceback(e.__traceback__)
    return wrapper


class ApiHandler:

    __AUTH_KEY = None

    @classmethod
    def _is_auth_key(cls):
        """
        Checks if authentication key is already read into application
        :return: True or False
        """
        return True if cls.__AUTH_KEY else False

    @classmethod
    def _auth_key_file(cls):
        """
        Gets authentication key from file defined by environment variable 'APISTOCK_KEY_FILE'
        """
        try:
            # root_path is parent folder of folder containing api_handler.py
            root_path = os.path.dirname(os.path.realpath(__file__))
            root_path = os.path.dirname(root_path)
            file_path = get_environ_file_path("APISTOCK_KEY_FILE",
                                              root_path=root_path)
            with open(file_path) as f_r:
                key = f_r.readline()
                if key:
                    cls.__AUTH_KEY = key
                else:
                    raise KeyError(f"File {file_path} does not contain valid authentication key!")
        except KeyError as e:
            raise Exception('Check README.md file for more information.').with_traceback(e.__traceback__)

    @classmethod
    def _init_req(cls) -> requests.Session:
        s = requests.Session()
        s.headers.update({"X-Finnhub-Token": cls.__AUTH_KEY, 'Content-type': 'application/json'})
        return s

    @classmethod
    @api_request
    def request_test(cls, request: requests.Session, name=None):
        if name:
            api_url = f"https://finnhub.io/api/v1/search?q={name}"
        else:
            api_url = "https://finnhub.io/api/v1/search"
        response = request.get(api_url)
        return response.json()

    @classmethod
    @api_request
    def current_price(cls, request: requests.Session, name): #, start_date: datetime):
        # start_date_str = str(int(start_date.timestamp()))
        # end_date_str = str(int(datetime.today().timestamp()))
        # api_url = f"https://finnhub.io/api/v1/stock/candle?symbol={name}&resolution=D&from={start_date_str}&to={end_date_str}"
        api_url = f"https://finnhub.io/api/v1/quote?symbol={name}"
        response = request.get(api_url)
        return response.json()

    @classmethod
    def metals_get_current_price(cls, metal_name):
        header = {"x-access-token": "goldapi-1sj718l0f5hae6-io", "Content-Type": "application/json"}
        response = requests.get(f'https://www.goldapi.io/api/{metal_name}/USD', headers=header)
        # {'timestamp': 1646564733, 'metal': 'XAG', 'currency': 'USD', 'exchange': 'FOREXCOM',
        # 'symbol': 'FOREXCOM:XAGUSD', 'prev_close_price': 25.184, 'open_price': 25.184, 'low_price': 25.046,
        # 'high_price': 25.745, 'open_time': 1646352000, 'price': 25.711, 'ch': 0.527, 'chp': 2.09, 'ask': 25.74,
        # 'bid': 25.682}
        return response.json()


if __name__ == "__main__":
    pass
    '''
    ApiHandler.request_test("XAG/USD")
    ApiHandler.request_test("CME_GC1")
    ApiHandler.current_price("IBM")
    '''

     # Gold price
    print("Gold:")
    spot_price = ApiHandler.metals_get_current_price("XAU")['price']
    print(spot_price)
    phys_price = ApiHandler.current_price("PHYS")['c'] * 361291628 / 2849551
    print(phys_price)
    offset = 0
    print((spot_price-phys_price)/spot_price*100-offset)

    '''
    # Silver price
    print("Silver:")
    spot_price = ApiHandler.metals_get_current_price("XAG")['price']
    print(spot_price)
    pslv_price = ApiHandler.current_price("PSLV")['c'] * 434458699 / 154432234
    print(pslv_price)
    print((spot_price-pslv_price)/spot_price*100)
    '''

'''
    # Pallad & Platinium price
    print("Pallad & Platinium:")
    xpt_ammount = 53383
    xpd_ammount = 41899
    spot_xpt_value = ApiHandler.metals_get_current_price("XPT")['price'] * xpt_ammount
    spot_xpd_value = ApiHandler.metals_get_current_price("XPD")['price'] * xpd_ammount
    spot_value = spot_xpt_value + spot_xpd_value
    print(spot_value)
    sppp_value = ApiHandler.current_price("SPPP")['c'] * 9748015
    print(sppp_value)
    print((spot_value-sppp_value)/spot_value*100)
    # Currently SPPP has bug
'''